### ISSUE TITLE
Ready for use with serde?

### ISSUE THREAD

**Issue by evan-goode** [GCCFeli/bitvec_simd#1]
Hi, I'd like to be able to serialize and deserialize bitvecs via serde. I saw the latest commit [b513a38](https://github.com/GCCFeli/bitvec_simd/commit/b513a38943d283764749434f2b5ace1275538ccc) seems to make some progress towards that, but it's failing to build for me:

```
error[E0609]: no field `arr` on type `&wide::u64x4`
   --> src/lib.rs:214:5
    |
214 |     arr: [u64; 4]
    |     ^^^ unknown field

error[E0560]: struct `wide::u64x4` has no field named `arr`
   --> src/lib.rs:214:5
    |
214 |     arr: [u64; 4]
    |     ^^^ `wide::u64x4` does not have this field
```

I'm very new to Rust so I'm not totally sure what the problem is, but from inspecting `wide`, it looks like `u64x4` has a variety of possible underlying definitions depending on the SIMD features of the compile target.

Is serde support not ready yet, or am I perhaps just doing something wrong?

**Comment by GCCFeli** [comment]
Commit [b513a38](https://github.com/GCCFeli/bitvec_simd/commit/b513a38943d283764749434f2b5ace1275538ccc) is a temp version of serde function. New serde support has been updated and now it should work.
